#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=95
USE_PROCD=1

PROG=/usr/bin/xray
CONFIG=/etc/xray/config.json
ASSETS=/etc/xray

start_service() {
    [ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] && {
        echo "xray is already running, no need to start again"
        exit 1
    }

    # add route
    /sbin/ip route add local default dev lo table 100
    /sbin/ip rule add fwmark 1 table 100

    # procd requires running in Foreground
    procd_open_instance
    procd_set_param command ${PROG} --config=${CONFIG}
    procd_set_param user root # run service as user root
    # procd_set_param stdout 1 # forward stdout of the command to logd
    procd_set_param stderr 1 # same for stderr
    procd_set_param env XRAY_LOCATION_ASSET=${ASSETS}  # pass environment variables to your process
    procd_set_param limits nofile="65535 65535" # important! increase ulimit
    [ -e /proc/sys/kernel/core_pattern ] && {
        procd_append_param limits core="65535 65535"
    }
    procd_close_instance
}

stop_service() {
    /sbin/ip route del local default dev lo table 100
    /sbin/ip rule del table 100
}
